# Generated by Django 5.2.9 on 2026-04-12 12:07

from django.db import migrations, models


def backfill_step_type_notebook(apps, schema_editor):
    """Set step_type='NOTEBOOK' on all existing ExecutionStep rows."""
    ExecutionStep = apps.get_model("flows", "ExecutionStep")
    ExecutionStep.objects.filter(step_type__isnull=True).update(step_type="NOTEBOOK")


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0005_add_external_run_id"),
    ]

    operations = [
        # Phase 1: add nullable (no table-level default, no lock on large tables)
        migrations.AddField(
            model_name="executionstep",
            name="step_type",
            field=models.CharField(
                choices=[("NOTEBOOK", "Notebook"), ("MOJO", "Mojo")],
                max_length=20,
                null=True,
                blank=True,
            ),
        ),
        # Phase 2: backfill existing rows to 'NOTEBOOK'
        migrations.RunPython(
            backfill_step_type_notebook,
            reverse_code=migrations.RunPython.noop,
        ),
        # Phase 3: tighten to non-nullable with default='NOTEBOOK'
        migrations.AlterField(
            model_name="executionstep",
            name="step_type",
            field=models.CharField(
                choices=[("NOTEBOOK", "Notebook"), ("MOJO", "Mojo")],
                default="NOTEBOOK",
                max_length=20,
            ),
        ),
    ]
