repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: debug-statements
      - id: check-toml

  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout
        entry: nbstripout
        language: system
        files: ".*\\.ipynb$"
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types_or: [python, pyi]
      - id: djlint-reformat-django
        name: djlint-reformat-django
        entry: djlint --reformat --profile django
        language: system
        files: "backend/.*\\.html$"
      - id: djlint-django
        name: djlint-django
        entry: djlint --profile django
        language: system
        files: "backend/.*\\.html$"
