# Generated by Django 5.2.9 on 2026-04-15 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0005_userprofile_mcp_token_budget_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(default="My Dashboard", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="McpSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("tokens_budget", models.IntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="accounts.userapikey",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["user", "ended_at"], name="dashboard_m_user_id_bf8102_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("METRIC_CARD", "Metric Card"),
                            ("LINE_CHART", "Line Chart"),
                            ("BAR_CHART", "Bar Chart"),
                            ("TABLE", "Table"),
                            ("SCORE_DISTRIBUTION", "Score Distribution"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("config", models.JSONField(default=dict)),
                ("position_x", models.SmallIntegerField(default=0)),
                ("position_y", models.SmallIntegerField(default=0)),
                ("width", models.SmallIntegerField(default=2)),
                ("height", models.SmallIntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboard.userdashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["position_y", "position_x"],
                "indexes": [
                    models.Index(fields=["dashboard"], name="dashboard_d_dashboa_f6d996_idx")
                ],
            },
        ),
    ]
