# Generated by Django 5.2.9 on 2026-04-11 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        help_text="Target number of rows requested at generation time."
                    ),
                ),
                (
                    "seed",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Random seed for reproducibility. Leave blank for a random seed.",
                        null=True,
                    ),
                ),
                (
                    "s3_path",
                    models.CharField(
                        blank=True,
                        help_text="S3 key (without bucket prefix) for the generated data.parquet.",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="training_tr_status_e82ba8_idx"),
                    models.Index(fields=["-created_at"], name="training_tr_created_79e25f_idx"),
                ],
            },
        ),
    ]
