# Generated by Django 5.2.9 on 2026-04-11 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label, e.g. 'round_1'.", max_length=100
                    ),
                ),
                (
                    "optimisation_target",
                    models.CharField(
                        choices=[
                            ("GINI", "Gini Coefficient"),
                            ("KS", "KS Statistic"),
                            ("F1_REVIEW", "F1 (Review Class)"),
                        ],
                        default="GINI",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "candidate_weights",
                    models.JSONField(
                        blank=True,
                        help_text="Optimal weight dict — null until run completes.",
                        null=True,
                    ),
                ),
                (
                    "candidate_thresholds",
                    models.JSONField(
                        blank=True,
                        help_text="Optimal threshold dict — null until run completes.",
                        null=True,
                    ),
                ),
                ("val_gini", models.FloatField(blank=True, null=True)),
                ("val_ks", models.FloatField(blank=True, null=True)),
                ("val_f1_review", models.FloatField(blank=True, null=True)),
                ("umap_enabled", models.BooleanField(default=False)),
                (
                    "artefacts_s3_path",
                    models.CharField(
                        blank=True,
                        help_text="S3 prefix for run artefacts (weights.json, thresholds.json, etc.).",
                        max_length=500,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_runs",
                        to="training.trainingdataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["dataset", "-created_at"], name="tr_run_ds_created_idx")
                ],
            },
        ),
    ]
