# Generated by Django 5.2.9 on 2026-04-11 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0002_modeltrainingrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelBacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("precision_approved", models.FloatField(blank=True, null=True)),
                ("precision_review", models.FloatField(blank=True, null=True)),
                ("precision_declined", models.FloatField(blank=True, null=True)),
                ("recall_approved", models.FloatField(blank=True, null=True)),
                ("recall_review", models.FloatField(blank=True, null=True)),
                ("recall_declined", models.FloatField(blank=True, null=True)),
                ("f1_approved", models.FloatField(blank=True, null=True)),
                ("f1_review", models.FloatField(blank=True, null=True)),
                ("f1_declined", models.FloatField(blank=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("gini", models.FloatField(blank=True, null=True)),
                ("ks_statistic", models.FloatField(blank=True, null=True)),
                ("confusion_matrix", models.JSONField(blank=True, null=True)),
                (
                    "artefacts_s3_path",
                    models.CharField(
                        blank=True,
                        help_text="S3 prefix for backtest artefacts (test_scores.parquet).",
                        max_length=500,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "training_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_result",
                        to="training.modeltrainingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-training_run__created_at"],
            },
        ),
    ]
