# Generated by Django 5.2.9 on 2026-04-12 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0004_seed_scoring_model_v1"),
        ("training", "0003_modelbacktestresult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("promoted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional admin rationale for promotion."
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resulting_scoring_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_promotion",
                        to="flows.scoringmodel",
                    ),
                ),
                (
                    "training_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion",
                        to="training.modeltrainingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-promoted_at"],
            },
        ),
    ]
