# Generated by Django 5.2.9 on 2026-04-15 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mcp_token_budget",
            field=models.IntegerField(
                blank=True,
                help_text="Per-user token budget override for MCP sessions. Null = use MCP_SESSION_TOKEN_BUDGET setting.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="notify_on_failure",
            field=models.BooleanField(
                default=True, help_text="Notify when an execution reaches terminal FAILED status."
            ),
        ),
        migrations.CreateModel(
            name="UserApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ANTHROPIC", "Anthropic"),
                            ("LLAMA_OPENAI", "Llama (local, OpenAI-compatible)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "encrypted_key",
                    models.TextField(
                        blank=True,
                        help_text="Fernet-encrypted API key. Never returned to the frontend.",
                    ),
                ),
                (
                    "masked_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 characters of the key, stored unencrypted for display only.",
                        max_length=4,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="OpenAI-compatible base URL for local providers (e.g. http://localhost:11434/v1).",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="accounts_us_user_id_57cc3d_idx"
                    )
                ],
                "unique_together": {("user", "provider")},
            },
        ),
    ]
