"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env(DEBUG=(bool, False))

# Read .env file from project root
environ.Env.read_env(os.path.join(BASE_DIR.parent, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Third party
    "storages",
    "compressor",
    # Local apps
    "apps.core",
    "apps.accounts",
    "apps.flows",
    "apps.flags",
    "apps.training",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.accounts.context_processors.notification_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": env.db("DATABASE_URL")}


# Password hashing — Argon2id is the OWASP-recommended algorithm (ASVS 2.10.3).
# Fallback to PBKDF2 allows existing PBKDF2 hashes to verify; they are
# transparently re-hashed to Argon2id on next login.
# Requires: argon2-cffi (in pyproject.toml dependencies)
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

# django-compressor — disabled in development (COMPRESS_ENABLED defaults to not DEBUG)
COMPRESS_OFFLINE = False

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Authentication
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/flows/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# AWS S3 / RustFS Configuration
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_S3_REGION_NAME = env("AWS_S3_REGION", default="us-east-1")
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default=None)
AWS_STORAGE_BUCKET_NAME = env("DATA_LAKE_BUCKET")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = "private"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"

# Use S3 for default file storage (Django 4.2+ / django-storages 1.14+)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Data Lake bucket
DATA_LAKE_BUCKET = env("DATA_LAKE_BUCKET")

# DuckDB Configuration
DUCKDB_THREADS = env.int("DUCKDB_THREADS", default=4)
DUCKDB_MEMORY_LIMIT = env("DUCKDB_MEMORY_LIMIT", default="4GB")

# S3 presigned URL expiry in seconds (default: 1 hour)
DOWNLOAD_URL_EXPIRY_SECONDS = env.int("DOWNLOAD_URL_EXPIRY_SECONDS", default=3600)

# Celery
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = "UTC"

# Site URL — used in email links (no trailing slash)
SITE_URL = env("SITE_URL", default="http://localhost:8000")

# Notebooks / doit pipeline
NOTEBOOKS_DIR = BASE_DIR.parent / env("NOTEBOOKS_DIR", default="notebooks")
NOTEBOOK_OUTPUT_DIR = BASE_DIR.parent / env("NOTEBOOK_OUTPUT_DIR", default="data/notebook_outputs")

# Pipeline backend — "doit" (default) or "prefect"
PIPELINE_BACKEND = env("PIPELINE_BACKEND", default="doit")

# Prefect backend settings (only required when PIPELINE_BACKEND=prefect)
PREFECT_API_URL = env("PREFECT_API_URL", default="http://prefect-server:4200/api")
# Shared secret used to authenticate /internal/step-status/ callbacks from the Prefect worker
PREFECT_INTERNAL_SECRET = env("PREFECT_INTERNAL_SECRET", default="")
# Base URL the Prefect worker uses to reach this Django instance (internal Docker network)
DJANGO_INTERNAL_URL = env("DJANGO_INTERNAL_URL", default="http://web:8000")
# Prefect UI base URL — used to build the "View in Prefect" link in the execution detail page
PREFECT_UI_URL = env("PREFECT_UI_URL", default="http://localhost:4200")

# Mojo compute container URL (only required when any ExecutionStep has step_type=MOJO)
MOJO_COMPUTE_URL = env("MOJO_COMPUTE_URL", default="http://mojo-compute:8080")

# Redis
REDIS_URL = env("REDIS_URL")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
